SELECT
esi.ITEM_NUMBER AS "Item Code"
, esi.DESCRIPTION AS "Item Description"
, ium.UNIT_OF_MEASURE AS "Primary UOM"
, iodv.ORGANIZATION_NAME AS "Organization Name"
, ics.ITEM_CLASS_NAME  
, gcc.CONCATENATED_SEGMENTS AS "SALES Account"
, esi.PLANNER_CODE 
, esi.QTY_RCV_TOLERANCE 
, esi.CREATED_BY 
, esi.CREATION_DATE 
, esi.ENABLED_FLAG 
, NULL AS "Item Template"
, NULL AS "Assigned Category IDs"
FROM
  EGP_SYSTEM_ITEMS_V esi
LEFT JOIN
  GL_CODE_COMBINATIONS gcc ON gcc.CODE_COMBINATION_ID = esi.SALES_ACCOUNT
JOIN
  EGP_ITEM_CLASSES_VL ics ON esi.ITEM_CATALOG_GROUP_ID = ics.ITEM_CLASS_ID 
JOIN
  INV_UNITS_OF_MEASURE_VL ium ON esi.PRIMARY_UOM_CODE = ium.UOM_CODE
JOIN 
  inv_organization_definitions_v iodv ON iodv.ORGANIZATION_ID = esi.ORGANIZATION_ID
WHERE
 esi.ORGANIZATION_ID IS NOT NULL
 -- AND esi.ITEM_NUMBER = 'G3-00600003'
ORDER BY
esi.ITEM_NUMBER ASC